export const energidepolama_photo_mapping = {
    "video1": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/A+videosu.mp4",
    "photo1": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/B+FOTOG%CC%86RAFI+.jpg",
    "photo2": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/C+FOTOG%CC%86RAFI.jpg",
    "photo3": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/D+FOTOG%CC%86RAFI.jpg",
    "photo4": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/E+FOTOG%CC%86RAFI.jpg",
    "photo5": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/F+FOTOG%CC%86RAFI.jpg",
    "photo6": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/1.jpg",
    "photo7": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/2.jpg",
    "photo8": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/3.jpg",
    "photo9": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/4.jpg",
    "photo10": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/5.jpg",
    "photo11": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/6.jpg",
    "photo12": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/7.jpg",
    "photo13": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/8.jpg",
    "photo14": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/9.jpg",
    "photo15": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/10.jpg",
    "photo16": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/11.jpg",
    "photo17": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/12.jpg",
    "photo18": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/13.jpg",
    "photo19": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/14.jpg",
    "photo20": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/15.jpg",
    "photo21": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/16.jpg",
    "photo22": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/17.jpg",
    "photo23": "https://tekinpower.s3.eu-north-1.amazonaws.com/hizmetlerimiz/enerjidepolama/18.jpg",
}